config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :users
  resources :profiles
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  get 'friend_request/:id', to: 'friend_requests#friend_request', as: 'new_request'
  post 'accept_friend_request/:id', to: 'friend_requests#accept_friend_request', as: 'accept_request'
  post 'delete_friend_request/:id', to: 'friend_requests#delete_friend_request', as: 'delete_request'
  get 'friendship', to: 'users#index'

  get 'api/posts', to: 'api#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_admin_mail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :friendships, dependent: :destroy
  has_many :friend_requests, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def send_admin_mail
    UserMailer.with(user: self).welcome_email.deliver_later
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    @profile = Profile.where("user_id = ?", current_user.id)
    @friends_list = current_user.friendships
    @users = User.all
    @requests = FriendRequest.my_friend_requests(current_user)
    @my_requests = FriendRequest.friend_requests(current_user)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC")
    @post = @user.posts.build
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def user_gravatar(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/views/users/index.html.erb
<div class="d-flex container">
  <div class="d-flex flex-column p-4", style="width: 33%">
    <h1>Friends List</h1>
    <% current_user.friendships.each do |friend| %>
      <%= friend.inspect %>
      <%= button_to "delete friend", delete_request_path(friend) %>
    <% end %>
  </div>


  <div class="d-flex flex-column p-4", style="width: 33%">
    <h1>Pending Requests</h1>
    <% @my_requests.each do |my_requests| %>
      <%= my_requests.inspect %> <br/><br/>
    <% end %>
  </div>

  <div class="d-flex flex-column p-4", style="width: 33%">
    <h1>Add Friends</h1>
    <% @users.each do | potential_friend | %>
      <% unless potential_friend.id == current_user.id or current_user.friendships.current_friends(potential_friend).exists? or FriendRequest.my_friend_requests(potential_friend).exists? or FriendRequest.my_friend_requests(potential_friend).exists? %>
        <%= potential_friend.email %><br/><br>
        <%= button_to "Add Friend", new_request_path(potential_friend), method: :get %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="d-flex p-5">
  <%# profile section  %>
  <% if current_user.profile %>
    <div class="d-flex flex-column align-items-center justify-content-start">
      <h1 class="d-inline-flex mb-2">
        <%= current_user.profile.first_name %>
        <%= current_user.profile.last_name %>
      </h1>
      <div>
        <% if current_user.profile.avatar.attached? %>
            <%= image_tag current_user.profile.avatar.variant(resize_to_fill: [150, nil], saver: { quality: 100 }), class: 'rounded mb-2' %>
          <% else %>
            <%= image_tag user_gravatar(@user), class:"rounded" %>
        <% end %>
      </div>
      <p class="p-2">
        <b>Date Of Birth: </b><%= current_user.profile.dob.to_formatted_s(:long_ordinal) %>
      </p>
      <p class="p-2">
        <b>Address: </b><%= current_user.profile.address %>
      </p>
      <div>
        <%= link_to "Edit profile", edit_profile_path(current_user.profile), class:'btn btn-primary' %>
      </div>
    </div>

  <% else %>
    <div class="m-4" style="width: 17.37%, min-width: ">
      <%= link_to "Set up your profile", new_profile_path, class:'btn btn-primary' %>
    </div>
  <% end %>

  <%# post section %>

  <div class="d-flex flex-column align-items-center justify-content-center", style="width: 70%">
    <div class='mb-2' style='width: 35%'>
      <%= render 'posts/form' %>
    </div>
    <% if @posts.exists? %>
      

      <% @posts.each do | post | %>
        <div class="card mb-2 shadow", style="width: 60%">
        <p class="card-header text-center text-white bg-primary">
          <% if post.user.profile and post.user.profile.avatar.attached? %>
              <%= image_tag post.user.profile.avatar.variant(resize_to_fill: [50, 50], saver: { quality: 100 }).processed, class:"rounded" %>
            <% else %>
              <%= image_tag user_gravatar(post.user), class:"rounded" %>
          <% end %>
            <%= post.user.email%>
        </p>
          
          <% if current_user.posts.include?(post) %> 
            <%= link_to edit_post_path(post), class:"text-decoration-none" do %>
              <span class="bi bi-pencil-square text-black ps-2"></span>
            <% end %>
          <% end %>
          <div class="card-item p-3 text-center">
          <% if post.image.attached? %>
            <div>
              <%= image_tag post.image.variant(resize_to_fill: [350, nil], saver: { quality: 100 }), class: 'rounded mb-2' %>
            </div>
          <% end %>
            <div>
              <%= post.body%>
            </div>
          </div>

          <% already_liked = post.likes.find { | like | like.user_id == current_user.id } %> 
          <% if already_liked %>
            <%= button_to post_like_path(post_id: post.id, id: already_liked.id), data: {turbo: false }, method: :delete, class:"btn btn-link btn-md text-decoration-none p-0 ps-2 pb-2" do %>
              <span class="bi bi-hand-thumbs-up-fill">
                <%= post.likes.count unless post.likes.count == 0 %>
              </span>
            <% end %>
            <% else %>
            <%= button_to post_likes_path(post), method: :post, class:"btn btn-link text-decoration-none p-0 ps-2 pb-2" do %> 
              <span class="bi bi-hand-thumbs-up text-black">
                <%= post.likes.count unless post.likes.count == 0 %>
              </span>
            <% end %>
          <% end %>
          
          <%# comment section %>
          <div class='d-flex flex-column align-items-center'>
            <%= form_with model: [post, Comment.new] do | f | %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.text_field :body, class:"form-control", style:"width: 100%" %>
              <%= f.submit "Comment!", class:"btn btn-primary btn-sm mt-1 mb-3", style:"width: 100%" %>
            <% end %>
          </div>
          <% if post.comments.exists? %>
            <% post.comments.order("created_at DESC").each do | comment | %>
              <div class="card rounded m-2">
                <div class='card-title text-center bg-primary rounded-top text-white'>
                  <%= comment.user.email %>
                </div>
                <p class='text-center'>
                  <%= comment.body %>
                </p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>