config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :users
  resources :profiles
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  get 'friend_request/:id', to: 'friend_requests#friend_request', as: 'new_request'
  post 'accept_friend_request/:id', to: 'friend_requests#accept_friend_request', as: 'accept_request'
  post 'delete_friend_request/:id', to: 'friend_requests#delete_friend_request', as: 'delete_request'
  get 'friendship', to: 'users#index'

  get 'api/posts', to: 'api#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user

  scope :my_friend_requests, ->(id) { where("friend_id = ?", id) }
  scope :friend_requests, ->(id) { where("user_id = ?", id) }


  # scope :friend_requests, ->(id) { where( "friend_id = ?", id) }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_match_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_match_options)
  end

  def inverses
    self.class.where(inverse_match_options)
  end

  def inverse_match_options
    { user_id: friend_id, friend_id: user_id }
  end

  scope :current_friends, ->(id) { where("friend_id = ?", id) }
end

#just probs fixed friending. messed with Friendship --> no more status that was moved to 
# friend request -- bi direectional relationship seems to be working okay. 
# will need to fix ways to check if friend request is pending through friend request model
# will need to fix ways to check if you are friends with someone and display posts if they are (:

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar 
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_admin_mail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :friendships, dependent: :destroy
  has_many :friend_requests, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def send_admin_mail
    UserMailer.with(user: self).welcome_email.deliver_later
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC")
    @modified_posts = @posts.map do |post| {
      post: post,
      user: post.user,
      comments: post.comments.map {|comment| {user: comment.user, comment: comment}}
    }
    end
    respond_to do |format|
      format.json { render json: @modified_posts, status: 200 }
    end
  end

  def new
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    if @post.save
      redirect_to @post, notice: "Check out your post!"
    else
      render :new, notice: "Something went wrong"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post updated"
    else
      redirect_to :edit, notice: "Something went wrong"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path, notice: "Post deleted"
    else
      redirect_to root_path, notice: "Something went wrong"
    end
  end

  private
  
  def post_params
    params.require(:post).permit(:id, :body, :image)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    unless already_liked?
      @post.likes.create(user_id: current_user.id)
      redirect_to root_path, notice: "Liked!"
    end
  end

  def destroy
    if already_liked?
      @like = @post.likes.find(params[:id])
      @like.destroy
      flash[:notice] = "unliked!"
    end
    redirect_to root_path
  end

  private

  def already_liked?
    @post = Post.find(params[:post_id])
    @post.likes.where(user_id: current_user.id).exists?
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.new
    @users = User.all
    @posts = Post.all.order("created_at DESC")
    @comments = Comment.all.order("created_at DESC")
    @my_requests = FriendRequest.my_friend_requests(current_user)
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    if @post.save
      redirect_to @post, notice: "Check out your post!"
    else
      render :new, notice: "Something went wrong"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post updated"
    else
      redirect_to :edit, notice: "Something went wrong"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path, notice: "Post deleted"
    else
      redirect_to root_path, notice: "Something went wrong"
    end
  end

  private
  
  def post_params
    params.require(:post).permit(:id, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    @profile = Profile.where("user_id = ?", current_user.id)
    @friends_list = current_user.friendships
    @users = User.all
    @requests = FriendRequest.my_friend_requests(current_user)
    @my_requests = FriendRequest.friend_requests(current_user)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC")
    @post = @user.posts.build
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user, size=40)
    if user.profile and user.profile.avatar.attached?
      user.profile.avatar.variant(resize: "[#{size}, nil]")
    else
      user_gravatar(user)
    end 
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def is_a_friend(friend)
    Friendship.current_friends(friend.id, current_user.user_id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_gravatar(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-primary ">
  <div class="container-fluid">
    <%= link_to "Facebook", root_path,class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friendship_path, class:"nav-link active"%>
        </li>
        <li class="nav-item dropdown">
            <div class="nav-link active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Notifications
              <% if @requests %>
                <% unless @requests.count == 0 %>
                  <span class="badge text-bg-secondary ms-2">
                    <%= @requests.count %>
                  </span>
                <% end %>
              <% end %>
            </div>
          <ul class="dropdown-menu">
                <% if @requests %>
                <% @requests.each do |request| %>
                  <li class="m-2">
                    <p><%= User.find(request.user_id).email %></p>
                    <div class='d-flex'>
                      <%= button_to "accept", accept_request_path(request), class:"d-flex ms-2 me-2 btn btn-secondary" %>
                      <%= button_to "deny", delete_request_path(request), class:"d-flex ms-2 me-2 btn btn-secondary" %>
                    </div>
                  </li>
                <% end %>
              <% end %>
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms me-2">
        <li class="nav-item text-white">
          signed in as: <%= current_user.email %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>
        <ul class="navbar-nav mb-2 mb-lg-0 ms-4 me-2">
        <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class:"btn btn-secondary" %>
          </li>
        </ul>
  <% end %>
    </div>
  </div>
</nav>
<% if notice %>
  <p class="alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>